### ISSUE TITLE
Adjusting the correlation matrix of estimation error according to the real correlation signs.

### ISSUE THREAD

**Issue by harryyiheyang** [yinxiangwu/Debiased.MVMR.simulations#1]
Hi Yingxiang,

I am Yihe Yang and I am performing some simulations based on your codes. I would like to report one issue: it may be better to adujst the correlation matrix "P" and "P_full" according to the real correlation signs.

The related R code is:

P_full=P_full*sign(cor(cbind(par.beta.exposure,rawdat_mvmr$SBP_beta)))

Indeed, without applying this adjustment, I was not able to run MVMRcML. And when this adjustment is applied, all methods become more stable and also more similar. 

![plot_zoom_png](https://github.com/yinxiangwu/Debiased.MVMR.simulations/assets/96660799/290593ad-b22c-4702-bb83-ce2e06dcd575)

Thank you very much.

**Comment by yinxiangwu** [comment]
Hi Yihe,

Thanks for your comment. To clarify, the matrix P in the simulation code (i.e. the shared correlation matrix \Sigma in our manuscript) measures the sample overlap between exposure datasets. In the extreme case where individual exposure datasets have no overlapping samples, this P matrix becomes essentially a diagonal matrix. In our simulations, we set the off-diagonal terms to be 0.3 and 0.7, representing weak/moderate sample overlap, respectively. In any case, it should not be confused with the correlation between par.beta.exposure.

Hope this clarifies.

**Comment by yinxiangwu** [comment]
Yihe, in addition to my above comment, I tried your proposal yesterday flipping the sign of P matrix entries according to cor(par.beta.exposure) in the setting where D = 5.5 and rho = 0.7 (i.e. the weakest case in Table 1). Indeed, all estimators behave more similar as your figures illustrates. The results actually make sense because once we do the flipping, the IV strenght parameter, calculated by min(eigen(IV_strength_matrix/sqrt(p))$values), increases from 7.35 to 17.75. This means that overall IV strength becomes larger, and therefore all estimators behave better. Hope this helps.

**Comment by harryyiheyang** [comment]
Thank you for your reply. I made this change from the practical view,  as the correlation matrix of estimation errors should go to the same directions as genetic correlation matrix. 
Thank you for letting me know it essentially improves the IV strenghts.
